### ISSUE TITLE
page_views not being populated

### ISSUE THREAD

**Issue by raytio** [ownstats/ownstats#5]
Sorry I think I'm missing something fundamental, but `select  * from page_views` in Athena results in `Zero records returned.` The Lambda looks like it's running:
```
/aws/lambda/raytio-web-stats-dev-transformPageViews 2020/06/05/[$LATEST]f06611ccfe1644f7b020dc1169a32fad START RequestId: ef3653ca-364f-453d-95af-2d35c885f8ce Version: $LATEST
/aws/lambda/raytio-web-stats-dev-transformPageViews 2020/06/05/[$LATEST]f06611ccfe1644f7b020dc1169a32fad {"name":"ownstatsLogger","hostname":"169.254.215.69","pid":7,"requestId":"ef3653ca-364f-453d-95af-2d35c885f8ce","level":20,"msg":"Found keys in 'raytio-web-stats-logs/access-logs/year=2020/month=06/day=05/hour=18/', creating partition!","time":"2020-06-05T19:01:50.836Z","v":0}
/aws/lambda/raytio-web-stats-dev-transformPageViews 2020/06/05/[$LATEST]f06611ccfe1644f7b020dc1169a32fad {"name":"ownstatsLogger","hostname":"169.254.215.69","pid":7,"requestId":"ef3653ca-364f-453d-95af-2d35c885f8ce","level":20,"msg":"Inserting new data in table 'ownstats.page_views'","time":"2020-06-05T19:01:50.855Z","v":0}
/aws/lambda/raytio-web-stats-dev-transformPageViews 2020/06/05/[$LATEST]f06611ccfe1644f7b020dc1169a32fad {"name":"ownstatsLogger","hostname":"169.254.215.69","pid":7,"requestId":"ef3653ca-364f-453d-95af-2d35c885f8ce","level":20,"msg":"\n      INSERT INTO ownstats.page_views\n      SELECT \n        year as event_year,\n        month as event_month,\n        day as event_day,\n        cast(concat(cast(date as VARCHAR(10)), ' ', time) as TIMESTAMP) as event_timestamp,\n        location as edge_location,\n        el.city as edge_city,\n        el.state as edge_state,\n        el.country as edge_country,\n        cast(el.latitude as REAL) as edge_latitude,\n        cast(el.longitude as REAL) as edge_longitude,\n        url_decode(url_extract_parameter(qs, 'u')) as url,\n        url_decode(url_extract_parameter(qs, 'pa')) as path,\n        referrer,\n        url_decode(url_extract_parameter(qs, 'ua')) as user_agent,\n        url_decode(url_extract_parameter(qs, 'tz')) as timezone,\n        concat(url_extract_parameter(qs, 'w'), 'x', url_extract_parameter(qs, 'h')) as device_outer_resolution,\n        concat(url_extract_parameter(qs, 'iw'), 'x', url_extract_parameter(qs, 'ih')) as device_inner_resolution,\n        cast(url_decode(url_extract_parameter(qs, 'd')) as integer) as device_color_depth,\n        url_decode(url_extract_parameter(qs, 'p')) as device_platform,\n        cast(url_decode(url_extract_parameter(qs, 'm')) as integer) as device_memory,\n        cast(url_decode(url_extract_parameter(qs, 'c')) as integer) as device_cores,\n        url_decode(url_extract_parameter(qs, 'l')) as browser_language,\n        url_decode(url_extract_parameter(qs, 's')) as source,\n        url_decode(url_extract_parameter(qs, 'uso')) as utm_source,\n        url_decode(url_extract_parameter(qs, 'uca')) as utm_campaign,\n        url_decode(url_extract_parameter(qs, 'ume')) as utm_medium,\n        url_decode(url_extract_parameter(qs, 'uco')) as utm_content,\n        url_decode(url_extract_parameter(qs, 'ute')) as utm_term,\n        result_type as cloudfront_cache_type,\n        cast(time_taken*1000 as integer) as cloudfront_time_taken_ms,\n        http_version as cloudfront_http_version,\n        cast(date as VARCHAR) as event_date,\n        hour as event_hour,\n        url_decode(url_extract_parameter(qs, 'hn')) as domain_name\n      FROM (\n        SELECT\n          concat(uri, '?', querystring) as qs,\n          *\n        FROM \n          ownstats.access_logs\n        WHERE year = '2020'\n          AND month = '06'\n          AND day = '05'\n          AND hour = '18'\n          AND uri = '/hello.gif'\n          AND querystring <> '-'\n          AND position('t=pv' IN querystring) > 0\n        ) l\n      INNER JOIN\n        ownstats.edge_locations el\n      ON \n        el.edge_location_prefix=substr(l.location, 1, 3)\n      ","time":"2020-06-05T19:01:50.855Z","v":0}
/aws/lambda/raytio-web-stats-dev-transformPageViews 2020/06/05/[$LATEST]f06611ccfe1644f7b020dc1169a32fad {"name":"ownstatsLogger","hostname":"169.254.215.69","pid":7,"requestId":"ef3653ca-364f-453d-95af-2d35c885f8ce","level":20,"msg":"MSCK REPAIR TABLE ownstats.page_views","time":"2020-06-05T19:01:50.856Z","v":0}
/aws/lambda/raytio-web-stats-dev-transformPageViews 2020/06/05/[$LATEST]f06611ccfe1644f7b020dc1169a32fad 2020-06-05T19:02:02.096Z       ef3653ca-364f-453d-95af-2d35c885f8ce    INFO    Query 5078b56e-ef73-4fc5-ae9e-f15ba318b1dc succeeded
/aws/lambda/raytio-web-stats-dev-transformPageViews 2020/06/05/[$LATEST]f06611ccfe1644f7b020dc1169a32fad 2020-06-05T19:02:04.040Z       ef3653ca-364f-453d-95af-2d35c885f8ce    INFO    Query e397801c-71cf-4020-a1c2-5489d4567097 succeeded
/aws/lambda/raytio-web-stats-dev-transformPageViews 2020/06/05/[$LATEST]f06611ccfe1644f7b020dc1169a32fad END RequestId: ef3653ca-364f-453d-95af-2d35c885f8ce
```
There are records in the `access_logs` and `edge_locations` tables.

Any suggestions on how to troubleshoot this further would be appreciated.

**Comment by tobilg** [comment]
Thanks for reporting, and sorry again for the inconvenience. This was fixed in https://github.com/ownstats/ownstats/commit/0ee3f7b8bce1dc96ca033131b3e50c7cbf2b4b06. Please do a `git pull` locally, and an `sls deploy` (followed by a `sls s3sync`) again.

This should update the `hello.js` script and pass the `t=pv` parameter that was missing before, and led to the SQL resultset being empty (see https://github.com/ownstats/ownstats/blob/master/functions/transformPageViews.js#L86)

**Comment by raytio** [comment]
No need to apologise. I really appreciate you providing support and making this project available!

Unfortunately  `page_views` is still not populated. I think it is related to #6 because the query is trying to match `AND uri = '/hello.gif'` but no such records exist in `access_logs`. Only "/hello.js" and "/robots.txt" exist.

**Comment by tobilg** [comment]
This seems connected to #6. If the path to the hello.gif is not correct, there will be no page views recorded. Will push a fix tomorrow. Thanks again

**Comment by tobilg** [comment]
This was fixed in 42d75aec63ac00364ba2f74da2fc72c0961ad217. Please do a `sls deploy`, and a `sls s3sync` again.
